//Try, On

//void main() {
//   try {
//     var division = 10 ~/ 0;
//     print(division);
//   } catch (e){
//     print(e);
//   }
// }


// Try, On, Catch

// void main() {
//   try {
//     var division = 10 ~/ 0;
//     print(division);
//   } on IntegerDivisionByZeroException{
//     print('Enter a amount which is greater than 0');
//   } catch (e){
//     print(e);
//   }
// }


// Custom Exception





